Base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Datos.urls')),
]

Datos/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    ## PANTALLA DE INICIO
    path('', views.Inicio, name='Inicio'),

    ## REGISTRAR PERSONA, AREA
    path('R_Area/', views.Area_U, name='R_Area'),
    path('R_Persona/', views.Persona_U, name='R_Persona'),
    path('buscar_Persona/', views.buscar_Persona, name='buscar_Persona'),

    path('Lista/the/personas/', views.Listado_Personas, name='Listado_Personas'),

    path('Edit_Persona/<int:producto_id>/', views.Editar_Persona, name='Editar_Persona'),


    path('E_Tonner/', views.E_Recarga, name='E_Tonner'),    

    ## TONER DISPONIBLE
    path('R_Tonner/', views.Tonner_U, name='R_Tonner'),
    path('L_Tonner/', views.E_Libre, name='L_Tonner'),
    path('buscar_Toners/', views.buscar_toners, name='buscar_Toners'),

    ## EDITAR TONER
    path('ED_Tonner/<int:producto_id>/', views.Editar_Tonner, name='ED_Tonner'),    

    ## TABLAS DE IMPRESORAS
    path('Tabla_Impresoras_OFC/', views.Tabla_Impresoras_OFC, name='Tabla_Impresoras_OFC'),
    path('Tabla/Impresoras/Municipios/', views.Tabla_D_Toners_Municipios, name='Tabla_D_Toners_Municipios'),
    path('Ver_Tabla_OFP/', views.Ver_Tabla_OFP, name='Ver_Tabla'),
    path('Ver_Tabla_Municipios/', views.ver_tabla_municipios, name='Ver_Tabla_Municipios'),
    path('buscar_T_OFP/', views.buscar_T_OFP, name='buscar_T_OFP'),
    path('buscar_Tabla_T_Toners_Municipios/', views.buscar_Tabla_T_Toners_Municipios, name='buscar_Tabla_T_Toners_Municipios'),

    ## EDITAR TABLAS
    path('editar_t_municipios/<int:producto_id>/', views.editar_t_municipios, name='editar_t_municipios'),
    path('Tabla_T_Toners_OFP/<int:producto_id>/', views.Tabla_T_Toners_OFP, name='Tabla_T_Toners_OFP'),

    ## DETALLES E INFORMACION DE TABLAS OFC Y MUNICIPIOS
    path('detalles_T_OFP/', views.detalles_T_OFP, name='detalles_T_OFP'),
    path('detalles_T_Municipios/', views.detalles_T_Municipios, name='detalles_T_Municipios'),



    ## RETIRO DE TONNERS
    path('retirar_Tonner/<int:producto_id>/', views.RetiroTonner, name='retiroTonner'),
    path('toners-retirados/<int:producto_id>/', views.detalle_retiro_toner, name='detalle_retiro_toner'),
    path('V_Toners_R/', views.Buscar_Retiro, name='buscar_retiro'),

    ## Reacargar
    path('add_lista_de_recarga/<int:producto_id>/', views.add_Lista_de_Recarga, name='add_lista_de_recarga'),
    path('eliminar_de_lista_recarga/<int:producto_id>/', views.eliminar_de_lista_recarga, name='eliminar_de_lista_recarga'),
    path('ver_carrito/', views.ver_carrito, name='ver_carrito'),
    path('Toner_Recarga/', views.Toner_Recarga, name='Toner_Recarga'),
    path('detalles_toner/<int:producto_id>/', views.detalles_toner, name='detalles_toner'),

    path('guardar-recargas/', views.guardar_recargas, name='guardar_recargas'),
    path('pagina-exitosa/', views.pagina_exitosa, name='pagina_exitosa'),
    path('buscar_toners_R/', views.buscar_toners_R, name='buscar_toners_R'),

    ## LISTA DE TONERS POR ENTREGAR A SEAPTO
    path('Lista_T_Pendientes/', views.Lista_T_Pendientes, name='Lista_T_Pendientes'),
    path('recibir-toner/<int:toner_recargado_id>/', views.recibir_toner, name='recibir_toner'),

    ## DESCARGAR PDF DE MANUAL DE USUARIO
    path('download-pdf/', views.download_pdf, name='download_pdf'),

    ##Area
    path('Lista_Areas/', views.Lista_Areas, name='Lista_Areas'),
    path('Buscar_Area/', views.Buscar_Area, name='Buscar_Area'),
    path('Editar_Area/<int:producto_id>/', views.Editar_Area, name='Editar_Area'),

    ## Reportes
    path('reporte/excel/', views.generar_reporte_excel, name='generar_reporte_excel'),

    ## Cerrar servidor

    path('cerrar-servidor/', views.cerrar_servidor, name='cerrar_servidor'),


    ## Buscar toner pendientes
    path('Buscar_T_Recargando/', views.Buscar_T_Recargando, name='Buscar_T_Recargando'),

    ## OFF_SERVER.

    path('OFF_SERVER/', views.OFF_SERVER, name='OFF_SERVER'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Datos/models.py
from django.db import models, transaction
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError

## USUARIO ⬇ ---------------------------------------------------------------------------------------------
class Area(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.nombre

    def clean(self):
        if Area.objects.filter(nombre=self.nombre).exclude(pk=self.pk).exists():
            raise ValidationError('Ya existe un área con este nombre.')
    
    def save(self, *args, **kwargs):
        self.nombre = self.nombre.upper()   
        super(Area, self).save(*args, **kwargs)

class Persona(models.Model):
    nombre = models.CharField(max_length=100)
    firma = models.ImageField(upload_to='firmas/')
    area = models.ForeignKey(Area, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__( self ):
        return self.nombre

    def clean(self):
        if Persona.objects.filter(nombre=self.nombre, area=self.area).exclude(pk=self.pk).exists():
            raise ValidationError('Ya existe una persona con este nombre en esta área.')

    def save(self, *args, **kwargs):
        self.nombre = self.nombre.upper()   
        super(Persona, self).save(*args, **kwargs)
## USUARIO ⬆ ---------------------------------------------------------------------------------------------

## TONER ⬇ ---------------------------------------------------------------------------------------------
class Tonner(models.Model):
    ESTADO_T = [
        ('Disponible', 'Disponible'),
    
    ]


    nombre = models.CharField(max_length=50)
    cantidad = models.PositiveBigIntegerField()
    Numero_Toner = models.CharField(max_length=20)
    Estado = models.CharField(max_length=10, choices=ESTADO_T, default='Disponible')
    imagen = models.ImageField()
    
    def __str__(self):
        return f"{self.nombre}"


    def is_libre(self):
        return self.Estado == 'Disponible'
    
    def save(self, *args, **kwargs):
        self.nombre = self.nombre.upper()   
        super(Tonner, self).save(*args, **kwargs)



class Retiro_Tonner(models.Model):
    r_tonner = models.ForeignKey(Tonner, on_delete=models.SET_NULL, null=True, blank=True)
    r_persona = models.ForeignKey(Persona, on_delete=models.PROTECT, null=False, blank=False)
    cantidad_disponible = models.PositiveIntegerField(default=1)  
    cantidad_retirada = models.PositiveIntegerField(default=1)
    caso_GLPI = models.CharField(max_length=100, default='En Espera')
    descripcion = models.TextField(max_length=500, default='Sin descripción')
    fecha_retiro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.r_persona} - {self.r_tonner}"
    



## TONER ⬆ ---------------------------------------------------------------------------------------------

## RECARGA DE TONER ⬇ ------------------------------------------------------------------------------------

class Recargar_Toner(models.Model):
    toner = models.ForeignKey(Tonner, on_delete=models.SET_NULL, null=True, blank=True)
    cantidad_Recargar = models.PositiveIntegerField()
    fecha_Recarga = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.toner} - Recargando"
    
## RECARGA DE TONER ⬆ ------------------------------------------------------------------------------------


## TABLA TONER OFICINA PRINCIPAL IBAGUE ⬇ ---------------------------------------------------------------------------------------------

class Tabla_T_Toners(models.Model):
    MARCA_I = [
        ('N/A','N/A'),
        ('HP','HP'),
        ('SAMSUNG','SAMSUNG'),
        ('KYOSERA','KYOSERA'),
        ('EPSON','EPSON'),
    ]

    T_TONER = [
        ('105A','105A'),
        ('30A','30A'),
        ('83A','83A'),
        ('136A','136A'),
        ('175A','175A'),
        ('17A','17A'),
        ('19A','19A'),
        ('85A','85A'),
        ('226A','226A'),
        ('D1015','D1015'),
        ('TINTA','TINTA'),
        ('N/A','N/A'),
    ]

    oficina = models.CharField(max_length=50)
    activo = models.CharField(max_length=30)
    numero_impresoras = models.PositiveIntegerField()
    referencia = models.CharField(max_length=100)
    marca = models.CharField(max_length=7, choices=MARCA_I, default='N/A')
    toner_de_impresora = models.CharField(max_length=5, choices=T_TONER, default='N/A')
    otro_toner = models.CharField(max_length=5, choices=T_TONER, default='N/A')
    cantidad_toner = models.PositiveBigIntegerField()

    def __str__(self) -> str:
        return f"{self.oficina} {self.marca}"
    
    def clean(self):
        if Tabla_T_Toners.objects.filter(oficina=self.oficina, activo=self.activo).exclude(pk=self.pk).exists():
            raise ValidationError('Ya existe se encuentra registrada')
        
    def save(self, *args, **kwargs):
        self.oficina = self.oficina.upper()   
        super(Tabla_T_Toners, self).save(*args, **kwargs)

    
## TABLA TONER OFICINA PRINCIPAL IBAGUE ⬆ ---------------------------------------------------------------------------------------------


## TABLA TONER MUNICIPIOS ⬇ ---------------------------------------------------------------------------------------------

class Tabla_T_Toners_Municipios(models.Model):
    MARCA_I = [
        ('N/A','N/A'),
        ('HP','HP'),
        ('SAMSUNG','SAMSUNG'),
        ('KYOSERA','KYOSERA'),
        ('EPSON','EPSON'),
    ]

    T_TONER = [
        ('105A','105A'),
        ('30A','30A'),
        ('83A','83A'),
        ('136A','136A'),
        ('175A','175A'),
        ('17A','17A'),
        ('19A','19A'),
        ('85A','85A'),
        ('226A','226A'),
        ('D1015','D1015'),
        ('MLT-D1018','MLT-D1018'),
        ('101S','101S'),
        ('TINTA','TINTA'),
        ('N/A','N/A'),
    ]

    Y_N = [
        ('SI','SI'),
        ('NO','NO'),
        ('REGISTRAR','REGISTRAR'),
    ]
    
    ZONA = [
        ('SIN DEFINIR', 'SIN DEFINIR'),
        ('SUR', 'SUR'),
        ('NORTE', 'NORTE'),
        ('ALEDAÑOS', 'ALEDAÑOS'),
    ]

    oficina = models.CharField(max_length=50)
    activo = models.CharField(max_length=30)
    numero_impresoras = models.PositiveIntegerField()
    referencia = models.CharField(max_length=100)
    marca = models.CharField(max_length=7, choices=MARCA_I, default='N/A')
    toner_de_impresora = models.CharField(max_length=9, choices=T_TONER, default='N/A')
    otro_toner = models.CharField(max_length=9, choices=T_TONER, default='N/A')
    cantidad_toner = models.PositiveBigIntegerField()
    comprobado = models.CharField(max_length=9, choices=Y_N, default='SI')
    zona = models.CharField(max_length=11, choices=ZONA, default='SIN DEFINIR')

    def __str__(self) -> str:
        return f"{self.oficina} - {self.marca}"
    
    def clean(self):
        if Tabla_T_Toners_Municipios.objects.filter(oficina=self.oficina, activo=self.activo).exclude(pk=self.pk).exists():
            raise ValidationError('Ya existe se encuentra registrada')
        
    def save(self, *args, **kwargs):
        self.oficina = self.oficina.upper()   
        super(Tabla_T_Toners_Municipios, self).save(*args, **kwargs)

## TABLA TONER MUNICIPIOS ⬆ ---------------------------------------------------------------------------------------------

##AÑADIR LOS TONER QUE ESTABAN EN RECARGANDO
class Toner_M_Recargados(models.Model):
    ESTADO = [
        ('ENTREGADO','ENTREGADO'),
        ('RECARGANDO','RECARGANDO'),
        ]
    toner = models.ForeignKey(Tonner, on_delete=models.SET_NULL, null=True, blank=True)
    cantidad = models.PositiveIntegerField()
    estado = models.CharField(max_length=10, choices=ESTADO, default='RECARGANDO')
    fecha_entrega = models.DateTimeField(auto_now_add=True, null=False)
    fecha_recibido = models.DateTimeField(null=True)

    def __str__(self) -> str:
        return f"se añade {self.cantidad} a el Toner {self.toner}"
    
@receiver(post_save, sender=Toner_M_Recargados)
def actualizar_estado_toner(sender, instance, created, **kwargs):
    if instance.estado == 'ENTREGADO':
        toner = instance.toner
        toner.cantidad += instance.cantidad
        toner.save()
##AÑADIR LOS TONER QUE ESTABAN EN RECARGANDO

Datos/forms.py
from typing import Any
from django import forms
from .models import Area, Persona, Tonner, Retiro_Tonner, Tabla_T_Toners, Tabla_T_Toners_Municipios, Recargar_Toner
import base64
from django.core.files.base import ContentFile

class FormArea(forms.ModelForm):
    class Meta:
        model = Area
        fields = '__all__'

class FormPersona(forms.ModelForm):
    firma_imagen = forms.CharField(widget=forms.HiddenInput(), required=False)
    class Meta:
        model = Persona
        fields = ['nombre', 'area', 'firma_imagen']

    def save(self, commit=True):
        persona = super().save(commit=False)
        firma_imagen = self.cleaned_data.get('firma_imagen')

        if firma_imagen:
            format, imgstr = firma_imagen.split(';base64,')
            ext = format.split('/')[-1]
            persona.firma.save(f'firma_{persona.nombre}.{ext}', ContentFile(base64.b64decode(imgstr)), save=False)

        if commit:
            persona.save()

        return persona
    

class FormTonner(forms.ModelForm):
    class Meta:
        model = Tonner
        fields = '__all__'

class FormsRetiroTonner(forms.ModelForm):
    class Meta:
        model = Retiro_Tonner
        fields = ['r_persona', 'cantidad_retirada', 'caso_GLPI', 'descripcion']

class FormsTabla_Toners(forms.ModelForm):
    class Meta:
        model = Tabla_T_Toners
        fields = '__all__'

class FormsTabla_Toners_Municipios(forms.ModelForm):
    class Meta:
        model = Tabla_T_Toners_Municipios
        fields = '__all__'

class formsRecargando(forms.ModelForm):
    class Meta:
        model = Recargar_Toner
        fields = '__all__'

        

Datos/templates/registro/R_Area.html
{% extends 'layouts/base.html' %}

{% block content %}
{% load static %}

{% include 'layouts/Barra_user.html'%}
<head>
    <title>Registro Area</title>
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/ALL.css' %}">
</head>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="link-container" style="display: flex; justify-content: space-evenly;">
    <a href="{% url 'Lista_Areas' %}" class="styled-link">Lista de Areas</a>
</div>
<center>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">Agregar</button>
    </form>
</center>
<style>
    form {
        display: flex;
        margin: 20px; 
        padding: 50px; 
        border: 1px solid #ccc; 
        background-color: #f9f9f9; 
        justify-content: space-evenly;
    }

    .styled-link {
    text-decoration: none;
    color: #045cab;
    padding: 10px;
    border: 1px solid #045cab;
    border-radius: 5px;
}

  .styled-link:hover {
    background-color: #045cab;
    color: white;
  }

</style>

{% endblock %}

Datos/templates/registro/R_Persona.html
{% extends 'layouts/base.html' %}

{% block content %}
{% load static %}

{% include 'layouts/Barra_user.html' %}

<head>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

  <!-- Incluir jQuery (necesario para Select2) -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <!-- Incluir JS de Select2 -->
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <title>Registro de Persona</title>
  <link rel="stylesheet" type="text/css" href="{% static 'CSS/ALL.css' %}">
</head>


<br>
<div class="container">
  <h2 style="text-align: center;">Registro de Persona</h2>
  <br>

  <div class="link-container" style="display: flex; justify-content: space-evenly;">
    <a href="{% url 'Listado_Personas' %}" class="styled-link">Lista de Personas</a>
  </div>

  <br>

  <form method="post" enctype="multipart/form-data" style="max-width: 600px; margin: 0 auto;">
    {% csrf_token %}
    <p>
      <label for="id_nombre">Nombre:</label>
      <input type="text" name="nombre" maxlength="100" required="" id="id_nombre">
    </p>

    <p>
      <label for="id_area">Area:</label>
      <select name="area" id="id_area" class="select2">
        <option value="" selected="">---------</option>
        {% for area in areas %}
          <option value="{{ area.id }}"> {{ area.nombre }} </option>
        {% endfor %}
  
      </select>      
    </p>

    <br>
    <hr>
    <br>

    <div style="margin-bottom: 20px;">
      <label for="firma" style="display: block; margin-bottom: 5px;">Firma:</label>
      <canvas id="canvas" width="400" height="200" style="border: 1px solid #ccc;"></canvas>
      <input type="hidden" id="firma_imagen" name="firma_imagen">
      <br>

      <button class="button" onclick="limpiarCanvas()">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 69 14" class="svgIcon bin-top">
          <g clip-path="url(#clip0_35_24)">
            <path fill="black"
              d="M20.8232 2.62734L19.9948 4.21304C19.8224 4.54309 19.4808 4.75 19.1085 4.75H4.92857C2.20246 4.75 0 6.87266 0 9.5C0 12.1273 2.20246 14.25 4.92857 14.25H64.0714C66.7975 14.25 69 12.1273 69 9.5C69 6.87266 66.7975 4.75 64.0714 4.75H49.8915C49.5192 4.75 49.1776 4.54309 49.0052 4.21305L48.1768 2.62734C47.3451 1.00938 45.6355 0 43.7719 0H25.2281C23.3645 0 21.6549 1.00938 20.8232 2.62734ZM64.0023 20.0648C64.0397 19.4882 63.5822 19 63.0044 19H5.99556C5.4178 19 4.96025 19.4882 4.99766 20.0648L8.19375 69.3203C8.44018 73.0758 11.6746 76 15.5712 76H53.4288C57.3254 76 60.5598 73.0758 60.8062 69.3203L64.0023 20.0648Z">
            </path>
          </g>
          <defs>
            <clipPath id="clip0_35_24">
              <rect fill="white" height="14" width="69"></rect>
            </clipPath>
          </defs>
        </svg>

        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 69 57" class="svgIcon bin-bottom">
          <g clip-path="url(#clip0_35_22)">
            <path fill="black"
              d="M20.8232 -16.3727L19.9948 -14.787C19.8224 -14.4569 19.4808 -14.25 19.1085 -14.25H4.92857C2.20246 -14.25 0 -12.1273 0 -9.5C0 -6.8727 2.20246 -4.75 4.92857 -4.75H64.0714C66.7975 -4.75 69 -6.8727 69 -9.5C69 -12.1273 66.7975 -14.25 64.0714 -14.25H49.8915C49.5192 -14.25 49.1776 -14.4569 49.0052 -14.787L48.1768 -16.3727C47.3451 -17.9906 45.6355 -19 43.7719 -19H25.2281C23.3645 -19 21.6549 -17.9906 20.8232 -16.3727ZM64.0023 1.0648C64.0397 0.4882 63.5822 0 63.0044 0H5.99556C5.4178 0 4.96025 0.4882 4.99766 1.0648L8.19375 50.3203C8.44018 54.0758 11.6746 57 15.5712 57H53.4288C57.3254 57 60.5598 54.0758 60.8062 50.3203L64.0023 1.0648Z">
            </path>
          </g>
          <defs>
            <clipPath id="clip0_35_22">
              <rect fill="white" height="57" width="69"></rect>
            </clipPath>
          </defs>
        </svg>
      </button>

    </div>

    <button type="submit" class="btn btn-primary" style="width: 100%;">Guardar</button>
  </form>
</div>

<style>
  /* SELECTOR DE AREA */
  .form-group {
            margin: 20px 0;
        }
        label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
        }
        select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
        }
        .select2-container .select2-selection--single {
            height: 38px;
        }
        .select2-container--default .select2-selection--single .select2-selection__rendered {
            line-height: 38px;
        }
        .select2-container--default .select2-selection--single .select2-selection__arrow {
            height: 38px;
        }
  /* SELECTOR DE AREA */
  
  .link-container {
    display: flex;
    justify-content: space-evenly;
}

  .styled-link {
      text-decoration: none;
      color: #045cab;
      padding: 10px;
      border: 1px solid #045cab;
      border-radius: 5px;
  }

  .styled-link:hover {
    background-color: #045cab;
    color: white;
  }

  #canvas {
    border: 1px solid #ccc;
    cursor: crosshair;
  }

  .btn {
    padding: 10px 20px;
    font-size: 16px;
    border-radius: 5px;
  }

  body {
    font-family: Arial, sans-serif;
    background-color: #f5f5f5;
  }

  h2 {
    text-align: center;
    color: #333;
  }
  

  form {
    background-color: #fff;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    width: 80%;
    margin: 0 auto;
  }

  label {
    display: block;
    margin-bottom: 8px;
    color: #666;
  }

  input[type="text"],
  input[type="email"],
  input[type="password"],
  select {
    width: 100%;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    margin-bottom: 15px;
    font-size: 16px;
  }

  #canvas {
    border: 1px solid #ccc;
    margin-bottom: 15px;
  }

  .button {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 12px 20px;
    border-radius: 4px;
    font-size: 16px;
    cursor: pointer;
  }

  .button:hover {
    background-color: #0056b3;
  }

  .button {
    width: 50px;
    height: 50px;
    border-radius: 50%;
    background-color: rgb(20, 20, 20);
    border: none;
    font-weight: 600;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.164);
    cursor: pointer;
    transition-duration: 0.3s;
    overflow: hidden;
    position: relative;
    gap: 2px;
  }

  .svgIcon {
    width: 12px;
    transition-duration: 0.3s;
  }

  .svgIcon path {
    fill: white;
  }

  .button:hover {
    transition-duration: 0.3s;
    background-color: rgb(255, 69, 69);
    align-items: center;
    gap: 0;
  }

  .bin-top {
    transform-origin: bottom right;
  }

  .button:hover .bin-top {
    transition-duration: 0.5s;
    transform: rotate(160deg);
  }
</style>

<script>
  var canvas = document.getElementById('canvas');
  var ctx = canvas.getContext('2d');
  var isDrawing = false;

  canvas.addEventListener('mousedown', startDrawing);
  canvas.addEventListener('mousemove', draw);
  canvas.addEventListener('mouseup', stopDrawing);

  function startDrawing(e) {
    isDrawing = true;
    ctx.beginPath();
    ctx.moveTo(e.clientX - canvas.offsetLeft, e.clientY - canvas.offsetTop);
  }

  function draw(e) {
    if (isDrawing) {
      ctx.lineTo(e.clientX - canvas.offsetLeft, e.clientY - canvas.offsetTop);
      ctx.stroke();
    }
  }

  function stopDrawing() {
    isDrawing = false;
    var imageData = canvas.toDataURL();
    document.getElementById('firma_imagen').value = imageData;
  }

  function limpiarCanvas() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    document.getElementById('firma_imagen').value = '';
  }

  $(document).ready(function() {
    $('.select2').select2({
      placeholder: "Selecciona un responsable"
    });
  });
</script>



{% endblock %}

Datos/templates/registro/R_Tonner.html
{% extends 'layouts/base.html' %}

{% block content %}
{% load static %}

<head>
    <title>Registro Toner</title>
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/ALL.css' %}">
</head>
<br>
<br>
<br>
<br>
<br>
<br>

<center>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit" class="btn">Agregar</button>
    </form>
</center>
<style>

        form {
            max-width: 400px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        h2 {
            text-align: center;
            color: #333333;
        }

        label {
            display: block;
            margin-bottom: 8px;
            color: #333333;
        }

        input[type="text"],
        input[type="number"],
        select {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #cccccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type="file"] {
            margin-top: 5px;
        }

        button {
            width: 100%;
            padding: 12px;
            border: none;
            border-radius: 4px;
            background-color: #007bff;
            color: #ffffff;
            font-size: 16px;
            cursor: pointer;
        }

        button:hover {
            background-color: #fff;
            color: black;
            border: 1px solid black;
        }

</style>


{% endblock %}